spring.profiles.active=dev
#spring.profiles.active=prod
#spring.profiles.active=windows

# ssh 远程执行py脚本
ssh.hostname=192.168.5.101
ssh.port=22
ssh.username=root
ssh.password=metoo89745000

py.prefix=cd /opt/sqlite/script &&
py.path=/opt/sqlite/script/
py.version=python3

spring.resttemplate.timeout.read=5000
spring.resttemplate.timeout.connection=5000