server.port=8389
server.servlet.context-path=/
spring.application.name=netmap

# SQLite数据库文件路径
sqlite.db.path=/opt/sqlite/install/mydatabase.db

PYPATH=/opt/sqlite/script
cf_scanner=/opt/sqlite/cf-scanner
os_scanner=/opt/sqlite/

AP.URL=http://127.0.0.1:8384/probeNmap/assignmentScanTask


task.switch.is-open=false

ssh.hostname=127.0.0.1
ssh.port=22
ssh.username=root
ssh.password=metoo89745000